### ISSUE TITLE
Add config onSave

### ISSUE THREAD

**Issue by pungggi** [snowcoders/sci-sort-import-groups#4]
Hello and thank you for this extension. Would you consider adding a configuration to allow autom. sorting on save?

**Comment by k2snowman69** [comment]
Hi @pungggi and thanks for opening an issue! I don't see any reason why we couldn't add that. Would you be willing to open a pull request? If not it may take us a few days to get to it... not this weekend but next weekend most likely.

**Comment by k2snowman69** [comment]
Just published 2.1.0, thanks for contributing!
