### ISSUE TITLE
Sorting within curly brackets 

### ISSUE THREAD

**Issue by peterbe** [snowcoders/sci-sort-import-groups#6]
In the readme there's the line `import {RadioGroup, RadioButton} from 'radio-group';` and it's same in input as the output. 

Shouldn't it *become* `import {RadioButton, RadioGroup} from 'radio-group';`?

**Comment by k2snowman69** [comment]
Yes it should; good catch! Just as an FYI though, this project has been [deprecated](https://github.com/snowcoders/sci-sort-import-groups#deprecation-notice) for quite a while (6 months or so) in favor of [sortier](https://github.com/snowcoders/sortier) and [sortier-vscode](https://github.com/snowcoders/sortier-vscode). I think the documentation on it's read me is correct.

If you would still like to fix this though, feel free to open a pull request!
